In [10]:
# pip install PyMuPDF

In [9]:
# import PyMuPDF

In [8]:
from function import *

In [1]:
import pandas as pd
import os
import arxiv

import urllib
from sklearn.metrics.pairwise import cosine_similarity


In [2]:
import fitz
import tensorflow_hub as hub


In [3]:
import numpy as np #not sure if this one is needed

# Preparation not always needed

In [4]:
loc_name_Arxiv = "pdftest\Term_Expansion_and_FinBERT_fine_tuning_for_Hypernym_and_Synonym_Ranking_of_Financial_Terms.pdf"
loc_name_Anth = "pdftest\Anth-Term Expansion and FinBERT fine-tuning for Hypernym and Synonym Ranking of Financial Terms.pdf"


doc_Arxiv = fitz.open(loc_name_Arxiv)
doc_Anth = fitz.open(loc_name_Anth)

IN the case of blocks:  extractBLOCKS()

    Textpage content as a list of text lines grouped by block. Each list items looks like this:

    (x0, y0, x1, y1, "lines in the block", block_no, block_type)

    The first four entries are the block’s bbox coordinates, block_type is 1 for an image block, 0 for text. block_no is the block sequence number. Multiple text lines are joined via line breaks.

    For an image block, its bbox and a text line with some image meta information is included – not the image content.

    This is a high-speed method with just enough information to output plain text in desired reading sequence.
    Return type:	list

In [5]:
table = pd.read_csv('combined_table.csv').drop('Unnamed: 0', axis =1)
test = table.head()

C:\Users\20193635\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (6,8) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)



In [6]:
test

ISBN address                                          booktitle  \
0  NaN  Online                                                NaN   
1  NaN  Online  Proceedings of the 5th Workshop on Online Abus...   
2  NaN  Online  Proceedings of the 5th Workshop on Online Abus...   
3  NaN  Online  Proceedings of the 5th Workshop on Online Abus...   
4  NaN  Online  Proceedings of the 5th Workshop on Online Abus...   

                         doi journal language   month note  number   pages  \
0                        NaN     NaN      NaN  August  NaN     NaN     NaN   
1  10.18653/v1/2021.woah-1.1     NaN      NaN  August  NaN     NaN    1--5   
2  10.18653/v1/2021.woah-1.2     NaN      NaN  August  NaN     NaN   6--16   
3  10.18653/v1/2021.woah-1.3     NaN      NaN  August  NaN     NaN  17--25   
4  10.18653/v1/2021.woah-1.4     NaN      NaN  August  NaN     NaN  26--35   

                                   publisher  \
0  Association for Computational Linguistics   
1  Association for Computational Linguistics   
2  Association for Computational Linguistics   
3  Association for Computational Linguistics   
4  Association for Computational Linguistics   

                                               title  \
0  Proceedings of the 5th Workshop on Online Abus...   
1  Exploiting Auxiliary Data for Offensive Langua...   
2  Modeling Profanity and Hate Speech in Social M...   
3  HateBERT: Retraining BERT for Abusive Language...   
4  Memes in the Wild: Assessing the Generalizabil...   

                                      url  volume  year  \
0  https://aclanthology.org/2021.woah-1.0     NaN  2021   
1  https://aclanthology.org/2021.woah-1.1     NaN  2021   
2  https://aclanthology.org/2021.woah-1.2     NaN  2021   
3  https://aclanthology.org/2021.woah-1.3     NaN  2021   
4  https://aclanthology.org/2021.woah-1.4     NaN  2021   

                                               clean  \
0  Proceedings of the 5th Workshop on Online Abus...   
1  Exploiting Auxiliary Data for Offensive Langua...   
2  Modeling Profanity and Hate Speech in Social M...   
3  HateBERT  Retraining BERT for Abusive Language...   
4  Memes in the Wild  Assessing the Generalizabil...   

                                         title_Arxiv  \
0                                                 NF   
1                                                 NF   
2  Modeling Profanity and Hate Speech in Social M...   
3  HateBERT: Retraining BERT for Abusive Language...   
4  Memes in the Wild: Assessing the Generalizabil...   

                       pdf_url_Arxiv            published_Arxiv  \
0                                NaN                        NaN   
1                                NaN                        NaN   
2  http://arxiv.org/pdf/2106.07505v2  2021-06-14 15:34:37+00:00   
3  http://arxiv.org/pdf/2010.12472v2  2020-10-23 15:14:14+00:00   
4  http://arxiv.org/pdf/2107.04313v1  2021-07-09 09:04:05+00:00   

                        result_Arxiv  
0                                NaN  
1                                NaN  
2  http://arxiv.org/abs/2106.07505v2  
3  http://arxiv.org/abs/2010.12472v2  
4  http://arxiv.org/abs/2107.04313v1

In [7]:
test.isna().sum()

ISBN               5
address            0
booktitle          1
doi                1
journal            5
language           5
month              0
note               5
number             5
pages              1
publisher          0
title              0
url                0
volume             5
year               0
clean              0
title_Arxiv        0
pdf_url_Arxiv      2
published_Arxiv    2
result_Arxiv       2
dtype: int64

In [11]:
test.columns

Index(['ISBN', 'address', 'booktitle', 'doi', 'journal', 'language', 'month',
       'note', 'number', 'pages', 'publisher', 'title', 'url', 'volume',
       'year', 'clean', 'title_Arxiv', 'pdf_url_Arxiv', 'published_Arxiv',
       'result_Arxiv'],
      dtype='object')

In [15]:
tab = prepare_table(test)
tab

title  year   month  \
2  Modeling Profanity and Hate Speech in Social M...  2021  August   
3  HateBERT: Retraining BERT for Abusive Language...  2021  August   
4  Memes in the Wild: Assessing the Generalizabil...  2021  August   

                                      url  \
2  https://aclanthology.org/2021.woah-1.2   
3  https://aclanthology.org/2021.woah-1.3   
4  https://aclanthology.org/2021.woah-1.4   

                                         title_Arxiv  \
2  Modeling Profanity and Hate Speech in Social M...   
3  HateBERT: Retraining BERT for Abusive Language...   
4  Memes in the Wild: Assessing the Generalizabil...   

                       pdf_url_Arxiv            published_Arxiv  \
2  http://arxiv.org/pdf/2106.07505v1  2021-06-14 15:34:37+00:00   
3  http://arxiv.org/pdf/2010.12472v1  2020-10-23 15:14:14+00:00   
4  http://arxiv.org/pdf/2107.04313v1  2021-07-09 09:04:05+00:00   

                        result_Arxiv  
2  http://arxiv.org/abs/2106.07505v2  
3  http://arxiv.org/abs/2010.12472v2  
4  http://arxiv.org/abs/2107.04313v1

In [56]:
urllib.request.urlretrieve(tab['pdf_url_Arxiv'][3], 'pdf sim/arx-'+tab['title'][3]+'.pdf')

('pdf sim/arx-HateBERT: Retraining BERT for Abusive Language Detection in English.pdf',
 <http.client.HTTPMessage at 0x26f9c1e3dc0>)

In [2]:
not_sample, sample = pdf_sim(embed, tab,max_iter = 2)

NameError: name 'embed' is not defined

In [207]:
not_sample

title  year   month  \
2  Modeling Profanity and Hate Speech in Social M...  2021  August   

                                      url  \
2  https://aclanthology.org/2021.woah-1.2   

                                         title_Arxiv  \
2  Modeling Profanity and Hate Speech in Social M...   

                       pdf_url_Arxiv            published_Arxiv  \
2  http://arxiv.org/pdf/2106.07505v1  2021-06-14 15:34:37+00:00   

                        result_Arxiv  
2  http://arxiv.org/abs/2106.07505v2

In [208]:
sample

title  year   month  \
4  Memes in the Wild: Assessing the Generalizabil...  2021  August   
3  HateBERT: Retraining BERT for Abusive Language...  2021  August   

                                      url  \
4  https://aclanthology.org/2021.woah-1.4   
3  https://aclanthology.org/2021.woah-1.3   

                                         title_Arxiv  \
4  Memes in the Wild: Assessing the Generalizabil...   
3  HateBERT: Retraining BERT for Abusive Language...   

                       pdf_url_Arxiv            published_Arxiv  \
4  http://arxiv.org/pdf/2107.04313v1  2021-07-09 09:04:05+00:00   
3  http://arxiv.org/pdf/2010.12472v1  2020-10-23 15:14:14+00:00   

                        result_Arxiv  Succes  w_Anth  w_Arxiv  w_both  \
4  http://arxiv.org/abs/2107.04313v1     1.0  4865.0   4840.0  4801.0   
3  http://arxiv.org/abs/2010.12472v2     1.0  4914.0   3763.0    52.0   

   pages_Anth  pages_Arxiv     cosin  len_blocks  len_Anth  len_Arxiv  
4        10.0         10.0  0.999624         1.0      12.0        3.0  
3         9.0          8.0  0.960287         1.0      10.0        8.0

In [209]:
not_sample, sample = pdf_sim(embed=embed, tab_old = not_sample, result=sample,max_iter = 1, r_state=2)



2    Modeling Profanity and Hate Speech in Social M...
Name: title, dtype: object
done url
start load
start blocks
remove_bar skipped
elem_both_list
length same element:  207
Join blocks
start embed/sim
start sim
Length Anthology: 14
Length Arxiv:6
Updated length Anthology: 46244
Updated length Arxiv:45732
                                                Anth  \
0  Proceedings of the Fifth Workshop on Online Ab...   

                                               Arxiv  
0  Modeling Profanity and Hate Speech in Social M...  
start cosin
0.999282 7037 6950 1 14 6
                                               title  year   month  \
2  Modeling Profanity and Hate Speech in Social M...  2021  August   

                                      url  \
2  https://aclanthology.org/2021.woah-1.2   

                                         title_Arxiv  \
2  Modeling Profanity and Hate Speech in Social M...   

                       pdf_url_Arxiv            published_Arxiv  \
2  http://arxiv.org

In [210]:
not_sample

Empty DataFrame
Columns: [title, year, month, url, title_Arxiv, pdf_url_Arxiv, published_Arxiv, result_Arxiv]
Index: []

In [211]:
sample

title  year   month  \
0  Modeling Profanity and Hate Speech in Social M...  2021  August   
1  Memes in the Wild: Assessing the Generalizabil...  2021  August   
2  HateBERT: Retraining BERT for Abusive Language...  2021  August   

                                      url  \
0  https://aclanthology.org/2021.woah-1.2   
1  https://aclanthology.org/2021.woah-1.4   
2  https://aclanthology.org/2021.woah-1.3   

                                         title_Arxiv  \
0  Modeling Profanity and Hate Speech in Social M...   
1  Memes in the Wild: Assessing the Generalizabil...   
2  HateBERT: Retraining BERT for Abusive Language...   

                       pdf_url_Arxiv            published_Arxiv  \
0  http://arxiv.org/pdf/2106.07505v1  2021-06-14 15:34:37+00:00   
1  http://arxiv.org/pdf/2107.04313v1  2021-07-09 09:04:05+00:00   
2  http://arxiv.org/pdf/2010.12472v1  2020-10-23 15:14:14+00:00   

                        result_Arxiv  Succes  w_Anth  w_Arxiv  w_both  \
0  http://arxiv.org/abs/2106.07505v2     1.0  7037.0   6950.0  6306.0   
1  http://arxiv.org/abs/2107.04313v1     1.0  4865.0   4840.0  4801.0   
2  http://arxiv.org/abs/2010.12472v2     1.0  4914.0   3763.0    52.0   

   pages_Anth  pages_Arxiv     cosin  len_blocks  len_Anth  len_Arxiv  
0        11.0         11.0  0.999282         1.0      14.0        6.0  
1        10.0         10.0  0.999624         1.0      12.0        3.0  
2         9.0          8.0  0.960287         1.0      10.0        8.0

# End function 
---
---
___

In [190]:
type(n), pd.DataFrame

(pandas.core.frame.DataFrame, pandas.core.frame.DataFrame)

In [188]:
n=pd.DataFrame()
if type(n) ==pd.DataFrame:
    print('x')

x


In [ ]:
embed, tab_old, result=None, max_iter=1, r_state = 2

In [152]:
try1.merge(try1,how='outer')

title  year   month  \
0  Memes in the Wild: Assessing the Generalizabil...  2021  August   
1  HateBERT: Retraining BERT for Abusive Language...  2021  August   

                                      url  \
0  https://aclanthology.org/2021.woah-1.4   
1  https://aclanthology.org/2021.woah-1.3   

                                         title_Arxiv  \
0  Memes in the Wild: Assessing the Generalizabil...   
1  HateBERT: Retraining BERT for Abusive Language...   

                       pdf_url_Arxiv            published_Arxiv  \
0  http://arxiv.org/pdf/2107.04313v1  2021-07-09 09:04:05+00:00   
1  http://arxiv.org/pdf/2010.12472v1  2020-10-23 15:14:14+00:00   

                        result_Arxiv  Succes  w_Anth  w_Arxiv  w_both  \
0  http://arxiv.org/abs/2107.04313v1     NaN  4865.0   4840.0  4801.0   
1  http://arxiv.org/abs/2010.12472v2     NaN  4914.0   3763.0    52.0   

   pages_Anth  pages_Arxiv     cosin  
0        10.0         10.0  0.999624  
1         9.0          8.0  0.960287

In [147]:
t[0]

title  year   month  \
2  Modeling Profanity and Hate Speech in Social M...  2021  August   

                                      url  \
2  https://aclanthology.org/2021.woah-1.2   

                                         title_Arxiv  \
2  Modeling Profanity and Hate Speech in Social M...   

                       pdf_url_Arxiv            published_Arxiv  \
2  http://arxiv.org/pdf/2106.07505v1  2021-06-14 15:34:37+00:00   

                        result_Arxiv  
2  http://arxiv.org/abs/2106.07505v2

In [73]:
embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")

In [91]:
def test_sim(embed, loc_name_Arxiv, loc_name_Anth):
#sometimes download not available. Then download works but does not give a good pdf so reading does not work
#         embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
        print('start load')
        doc_Arxiv = fitz.open(loc_name_Arxiv)
        doc_Anth = fitz.open(loc_name_Anth)
        
        print('start blocks')
        b_Anth = get_blocks(doc_Anth)
        b_Arxiv = get_blocks(doc_Arxiv)
        rect = (5,180,40,570)
        remove_bar = doc_Arxiv.load_page(0).get_text("text",clip=rect)
        try:
            b_Arxiv.remove(remove_bar)
        except:
            print('Unable to remove bar from arxiv')
    
        elem_both_list = set(b_Anth)&set(b_Arxiv)
        print('elem_both_list')
        print(elem_both_list)
        print('start join')
        #join blocks
#         p_Anth = join_diff(b_Anth, elem_both_list)
#         p_Arxiv = join_diff(b_Arxiv, elem_both_list)
        p_Anth = join_blocks(b_Anth, elem_both_list)
        p_Arxiv = join_blocks(b_Arxiv, elem_both_list)
    
        print('start embed')
        #similarity
            
        result = sim(p_Anth,p_Arxiv,embed)
        return result, b_Arxiv, b_Anth

In [92]:
test_sim_result = test_sim(embed, 'pdf Anth/Anth-Artificial Text Detection via Examining the Topology of Attention Maps.pdf',
                          'pdf Arxiv/2108.08375v1.Contributions_of_Transformer_Attention_Heads_in_Multi_and_Cross_lingual_Tasks.pdf')

start load
start blocks
Unable to remove bar from arxiv
elem_both_list
{'1\nIntroduction\n', 'References\n', 'Abstract\n'}
start join
start embed
start sim
Length Anthology: 4
Length Arxiv:4
                                                Anth  \
0  Contributions of Transformer Attention Heads i...   
1  Abstract This paper studies the relative impor...   
2  1 Introduction Prior research on mono-lingual ...   
3  References Xilun Chen, Ahmed Hassan Awadallah,...   

                                               Arxiv  
0  Proceedings of the 2021 Conference on Empirica...  
1  Abstract The impressive capabilities of recent...  
2  1 Introduction Recent text generation models (...  
3  References David Ifeoluwa Adelani, Haotian Mai...  


In [94]:
b_Arxiv = test_sim_result[1]
b_Anth = test_sim_result[2]

In [21]:
test_sim_result

(0.617386, 7288, 8302)

In [415]:
rect = (5,180,40,570)
doc_Arxiv.load_page(0).get_text("text",clip=rect)

'arXiv:2107.13764v1  [cs.CL]  29 Jul 2021\n'

In [426]:
# doc_Anth
# b_Anth = get_blocks(doc_Anth)
# b_Arxiv = get_blocks(doc_Arxiv)

rect = (5,180,40,570)
remove_bar = doc_Arxiv.load_page(0).get_text("text",clip=rect)
try:
    b_Arxiv.remove(remove_bar)
except:
    print('Unable to remove bar from arxiv')
                
# elem_both_list = set(b_Anth)&set(b_Arxiv)
# print('start join')
#join blocks
# p_Anth = join_blocks(b_Anth, elem_both_list)
# p_Arxiv = join_blocks(b_Arxiv, elem_both_list)
d_Anth = join_diff(b_Anth, elem_both_list)
d_Arxiv = join_diff(b_Arxiv, elem_both_list)
# print('start embed')

#similarity
# embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
# res = sim(d_Anth,d_Arxiv,embedding=embed)
# print(res)

In [46]:
tab['pdf_url_Arxiv']

2    http://arxiv.org/pdf/2106.07505v1
3    http://arxiv.org/pdf/2010.12472v1
4    http://arxiv.org/pdf/2107.04313v1
Name: pdf_url_Arxiv, dtype: object

In [78]:
embed

<tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject at 0x26fec337880>

In [49]:
tab

title  year   month  \
2  Modeling Profanity and Hate Speech in Social M...  2021  August   
3  HateBERT: Retraining BERT for Abusive Language...  2021  August   
4  Memes in the Wild: Assessing the Generalizabil...  2021  August   

                                      url  \
2  https://aclanthology.org/2021.woah-1.2   
3  https://aclanthology.org/2021.woah-1.3   
4  https://aclanthology.org/2021.woah-1.4   

                                         title_Arxiv  \
2  Modeling Profanity and Hate Speech in Social M...   
3  HateBERT: Retraining BERT for Abusive Language...   
4  Memes in the Wild: Assessing the Generalizabil...   

                       pdf_url_Arxiv            published_Arxiv  \
2  http://arxiv.org/pdf/2106.07505v1  2021-06-14 15:34:37+00:00   
3  http://arxiv.org/pdf/2010.12472v1  2020-10-23 15:14:14+00:00   
4  http://arxiv.org/pdf/2107.04313v1  2021-07-09 09:04:05+00:00   

                        result_Arxiv  
2  http://arxiv.org/abs/2106.07505v2  
3  http://arxiv.org/abs/2010.12472v2  
4  http://arxiv.org/abs/2107.04313v1

In [96]:
b_Anth

['Contributions of Transformer Attention Heads\nin Multi- and Cross-lingual Tasks\n',
 'Weicheng Ma1*, Kai Zhang2*†, Renze Lou3†, Lili Wang1, and Soroush Vosoughi4\n',
 '1,4Department of Computer Science, Dartmouth College\n2Department of Computer Science and Technology, Tsinghua University\n3Department of Computer Science, Zhejiang University City College\n1{first.last}.gr@dartmouth.edu\n2drogozhang@gmail.com\n3marionojump0722@gmail.com\n4soroush.vosoughi@dartmouth.edu\n',
 'Abstract\n',
 'This paper studies the relative importance of\nattention heads in Transformer-based models\nto aid their interpretability in cross-lingual and\nmulti-lingual tasks. Prior research has found\nthat only a few attention heads are important\nin each mono-lingual Natural Language Pro-\ncessing (NLP) task and pruning the remaining\nheads leads to comparable or improved per-\nformance of the model. However, the impact\nof pruning attention heads is not yet clear in\ncross-lingual and multi-lingual tasks. T

In [112]:
pand = pd.DataFrame()
pand['x']=[niew]
pand['x']

0    Contributions of Transformer Attention Heads\n...
Name: x, dtype: object

In [114]:
type(pand['x'][0])

str

In [107]:
pand['y']=['test']

In [108]:
pand

x     y
0  NaN  test

In [102]:
type(niew)

str

In [97]:
niew = " ".join(b_Anth)
len(niew)

47325

# use table of contents
possible to search table of contents in text


maybe assign blocks to toc


!!! selected arxiv code !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [4]:
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! gotten arxiv code selected
# rect = (0,0,75,500)
# page.get_text("text",clip=rect)

NameError: name 'page' is not defined

In [5]:
# page.get_textbox(rect)

In [4]:
doc_Arxiv

Document('pdf Arxiv\Term_Expansion_and_FinBERT_fine_tuning_for_Hypernym_and_Synonym_Ranking_of_Financial_Terms.pdf')

# after testing giving it a good try

In [41]:
l_Anth=[]
for i in doc_Anth.pages():
    l_Anth = l_Anth + i.get_text('blocks')

In [42]:
l_Anth

[(57.92100143432617,
  86.11181640625,
  554.0775146484375,
  120.71693420410156,
  'Term Expansion and FinBERT fine-tuning for Hypernym and Synonym Ranking\nof Financial Terms\n',
  0,
  0),
 (217.04800415039062,
  131.30752563476562,
  394.4539794921875,
  150.76959228515625,
  'Ankush Chopra∗† , Sohom Ghosh†\n',
  1,
  0),
 (192.7919921875,
  153.19454956054688,
  419.2077331542969,
  191.8687744140625,
  'Fidelity Investments, AI CoE, Bengaluru, India\n{ankush01729, sohom1ghosh}@gmail.com\n',
  2,
  0),
 (153.25799560546875,
  214.48614501953125,
  197.7425537109375,
  230.03961181640625,
  'Abstract\n',
  3,
  0),
 (73.92498779296875,
  235.214111328125,
  277.0807189941406,
  532.1502075195312,
  'Hypernym and synonym matching are one of the\nmainstream Natural Language Processing (NLP)\ntasks. In this paper, we present systems that at-\ntempt to solve this problem.\nWe designed these\nsystems to participate in the FinSim-3, a shared\ntask of FinNLP workshop at IJCAI-2021.\nThe\ns

In [43]:
l_Anth

[(57.92100143432617,
  86.11181640625,
  554.0775146484375,
  120.71693420410156,
  'Term Expansion and FinBERT fine-tuning for Hypernym and Synonym Ranking\nof Financial Terms\n',
  0,
  0),
 (217.04800415039062,
  131.30752563476562,
  394.4539794921875,
  150.76959228515625,
  'Ankush Chopra∗† , Sohom Ghosh†\n',
  1,
  0),
 (192.7919921875,
  153.19454956054688,
  419.2077331542969,
  191.8687744140625,
  'Fidelity Investments, AI CoE, Bengaluru, India\n{ankush01729, sohom1ghosh}@gmail.com\n',
  2,
  0),
 (153.25799560546875,
  214.48614501953125,
  197.7425537109375,
  230.03961181640625,
  'Abstract\n',
  3,
  0),
 (73.92498779296875,
  235.214111328125,
  277.0807189941406,
  532.1502075195312,
  'Hypernym and synonym matching are one of the\nmainstream Natural Language Processing (NLP)\ntasks. In this paper, we present systems that at-\ntempt to solve this problem.\nWe designed these\nsystems to participate in the FinSim-3, a shared\ntask of FinNLP workshop at IJCAI-2021.\nThe\ns

In [44]:
l_Arxiv=[]
for i in doc_Arxiv.pages():
    l_Arxiv = l_Arxiv + i.get_text('blocks')

In [45]:
l_Arxiv

[(57.92100143432617,
  86.11161804199219,
  554.0845336914062,
  120.71700286865234,
  'Term Expansion and FinBERT fine-tuning for Hypernym and Synonym Ranking\nof Financial Terms\n',
  0,
  0),
 (217.04800415039062,
  131.30734252929688,
  394.45404052734375,
  150.7696533203125,
  'Ankush Chopra∗† , Sohom Ghosh†\n',
  1,
  0),
 (192.7919921875,
  153.19436645507812,
  419.2115173339844,
  191.86895751953125,
  'Fidelity Investments, AI CoE, Bengaluru, India\n{ankush01729, sohom1ghosh}@gmail.com\n',
  2,
  0),
 (153.25799560546875,
  214.4859619140625,
  197.7432861328125,
  230.0396728515625,
  'Abstract\n',
  3,
  0),
 (73.92498779296875,
  235.2144775390625,
  277.0795593261719,
  532.1500854492188,
  'Hypernym and synonym matching are one of the\nmainstream Natural Language Processing (NLP)\ntasks. In this paper, we present systems that at-\ntempt to solve this problem.\nWe designed these\nsystems to participate in the FinSim-3, a shared\ntask of FinNLP workshop at IJCAI-2021.\nThe

In [46]:
lst_Arxiv = []
for el in l_Arxiv:
    if el[6]==0:
        lst_Arxiv.append(el[4])
lst_Arxiv

['Term Expansion and FinBERT fine-tuning for Hypernym and Synonym Ranking\nof Financial Terms\n',
 'Ankush Chopra∗† , Sohom Ghosh†\n',
 'Fidelity Investments, AI CoE, Bengaluru, India\n{ankush01729, sohom1ghosh}@gmail.com\n',
 'Abstract\n',
 'Hypernym and synonym matching are one of the\nmainstream Natural Language Processing (NLP)\ntasks. In this paper, we present systems that at-\ntempt to solve this problem.\nWe designed these\nsystems to participate in the FinSim-3, a shared\ntask of FinNLP workshop at IJCAI-2021.\nThe\nshared task is focused on solving this problem for\nthe financial domain. We experimented with var-\nious transformer based pre-trained embeddings by\nfine-tuning these for either classification or phrase\nsimilarity tasks. We also augmented the provided\ndataset with abbreviations derived from prospectus\nprovided by the organizers and definitions of the\nfinancial terms from DBpedia [Auer et al., 2007],\nInvestopedia, and the Financial Industry Business\nOntology (FIBO)

In [47]:
lst_Anth = []
for el in l_Anth:
    if el[6]==0:
        lst_Anth.append(el[4])
lst_Anth

['Term Expansion and FinBERT fine-tuning for Hypernym and Synonym Ranking\nof Financial Terms\n',
 'Ankush Chopra∗† , Sohom Ghosh†\n',
 'Fidelity Investments, AI CoE, Bengaluru, India\n{ankush01729, sohom1ghosh}@gmail.com\n',
 'Abstract\n',
 'Hypernym and synonym matching are one of the\nmainstream Natural Language Processing (NLP)\ntasks. In this paper, we present systems that at-\ntempt to solve this problem.\nWe designed these\nsystems to participate in the FinSim-3, a shared\ntask of FinNLP workshop at IJCAI-2021.\nThe\nshared task is focused on solving this problem for\nthe financial domain. We experimented with var-\nious transformer based pre-trained embeddings by\nfine-tuning these for either classification or phrase\nsimilarity tasks. We also augmented the provided\ndataset with abbreviations derived from prospectus\nprovided by the organizers and definitions of the\nfinancial terms from DBpedia [Auer et al., 2007],\nInvestopedia, and the Financial Industry Business\nOntology (FIBO)

In [48]:
for elem in lst_Arxiv:
    if elem in lst_Anth:
        print(elem)

Term Expansion and FinBERT fine-tuning for Hypernym and Synonym Ranking
of Financial Terms

Ankush Chopra∗† , Sohom Ghosh†

Fidelity Investments, AI CoE, Bengaluru, India
{ankush01729, sohom1ghosh}@gmail.com

Abstract

1
Introduction

∗Contact Author
†Equal Contribution

2
Related Works

Hypernym-hyponym extraction and learning text similarity
using semantic representations have been very challenging
areas of research for the NLP community. SemEval-2018
Task 9 [Camacho-Collados et al., 2018] was such an instance.

1https://spec.edmcouncil.org/fibo/
2https://sites.google.com/nlg.csie.ntu.edu.tw/finnlp2021/shared-
task-finsim (accessed on 8th July 2021)

Team CRIM [Bernier-Colborne and Barri`ere, 2018] per-
formed the best in this shared task. They combined a super-
vised word embedding based approach with an unsupervised
pattern discovery based approach. The FinSim shared tasks
[Maarouf et al., 2020; Mansar et al., 2021] deal with adopt-
ing these challenges specific to the Financial Domain.

In [51]:
elems_in_both_lists = set(lst_Anth) & set(lst_Arxiv)
elems_in_both_lists

{'1\nIntroduction\n',
 '1https://spec.edmcouncil.org/fibo/\n2https://sites.google.com/nlg.csie.ntu.edu.tw/finnlp2021/shared-\ntask-finsim (accessed on 8th July 2021)\n',
 '2\nRelated Works\n',
 '3\nProblem Statement\n',
 '4\nData\n',
 '4.1\nData Description\n',
 '6\nExperimentation and Results\n',
 'A callable bond (also called redeemable bond) is a type of bond (debt security) that allows\nthe issuer of the bond to retain the privilege of redeeming the bond at some point before\nthe bond reaches its date of maturity.\n',
 'Abstract\n',
 'Acronym expansion\n218\n',
 'Acronym expansion: As mentioned by Keswani et al.\n[Keswani et al., 2020], the presence of acronyms created a\nmajor issue in maintaining consistency. We used the abbre-\nviation extractor available in spaCy3[Honnibal et al., 2020]\npackage on the corpus of the prospectus to extract all the\nacronyms and their expansions. Upon manual inspection of\na sample output, we identified that not all the extracted items\nwere valid acr

In [15]:
for elem in lst_Anth:
    if elem not in elems_in_both_lists:
        print(elem)
for elem in lst_Arxiv:
    if elem not in elems_in_both_lists:
        print(elem)

Hypernym and synonym matching are one of the
mainstream Natural Language Processing (NLP)
tasks. In this paper, we present systems that at-
tempt to solve this problem.
We designed these
systems to participate in the FinSim-3, a shared
task of FinNLP workshop at IJCAI-2021.
The
shared task is focused on solving this problem for
the financial domain. We experimented with var-
ious transformer based pre-trained embeddings by
fine-tuning these for either classification or phrase
similarity tasks. We also augmented the provided
dataset with abbreviations derived from prospectus
provided by the organizers and definitions of the
financial terms from DBpedia [Auer et al., 2007],
Investopedia, and the Financial Industry Business
Ontology (FIBO). Our best performing system uses
both FinBERT [Araci, 2019] and data augmenta-
tion from the afore-mentioned sources.
We ob-
served that term expansion using data augmenta-
tion in conjunction with semantic similarity is ben-
eficial for this task and could b

In [16]:
n_Anth = []
join = ''
for y in lst_Anth:
    if y in elems_in_both_lists:
        if join != '':
            n_Anth.append(join)
            join = ''
        n_Anth.append(y)

    if y not in elems_in_both_lists:
        #store, join with next one and joined to n_list
        join += ' ' # add space
        join+=y

In [17]:
n_Anth

['Term Expansion and FinBERT fine-tuning for Hypernym and Synonym Ranking\nof Financial Terms\n',
 'Ankush Chopra∗† , Sohom Ghosh†\n',
 'Fidelity Investments, AI CoE, Bengaluru, India\n{ankush01729, sohom1ghosh}@gmail.com\n',
 'Abstract\n',
 ' Hypernym and synonym matching are one of the\nmainstream Natural Language Processing (NLP)\ntasks. In this paper, we present systems that at-\ntempt to solve this problem.\nWe designed these\nsystems to participate in the FinSim-3, a shared\ntask of FinNLP workshop at IJCAI-2021.\nThe\nshared task is focused on solving this problem for\nthe financial domain. We experimented with var-\nious transformer based pre-trained embeddings by\nfine-tuning these for either classification or phrase\nsimilarity tasks. We also augmented the provided\ndataset with abbreviations derived from prospectus\nprovided by the organizers and definitions of the\nfinancial terms from DBpedia [Auer et al., 2007],\nInvestopedia, and the Financial Industry Business\nOntology (FIBO

In [18]:
lst_Arxiv

['Term Expansion and FinBERT fine-tuning for Hypernym and Synonym Ranking\nof Financial Terms\n',
 'Ankush Chopra∗† , Sohom Ghosh†\n',
 'Fidelity Investments, AI CoE, Bengaluru, India\n{ankush01729, sohom1ghosh}@gmail.com\n',
 'Abstract\n',
 'Hypernym and synonym matching are one of the\nmainstream Natural Language Processing (NLP)\ntasks. In this paper, we present systems that at-\ntempt to solve this problem.\nWe designed these\nsystems to participate in the FinSim-3, a shared\ntask of FinNLP workshop at IJCAI-2021.\nThe\nshared task is focused on solving this problem for\nthe financial domain. We experimented with var-\nious transformer based pre-trained embeddings by\nfine-tuning these for either classification or phrase\nsimilarity tasks. We also augmented the provided\ndataset with abbreviations derived from prospectus\nprovided by the organizers and definitions of the\nfinancial terms from DBpedia [Auer et al., 2007],\nInvestopedia, and the Financial Industry Business\nOntology (FIBO)

In [19]:
len(n_Anth), len(lst_Anth)

(77, 109)

In [20]:
n_Arxiv = []
join = ''
for y in lst_Arxiv:
    if y in elems_in_both_lists:
        if join != '':
            n_Arxiv.append(join)
            join = ''
        n_Arxiv.append(y)

    if y not in elems_in_both_lists:
        #store, join with next one and joined to n_list
        join += ' ' # add space
        join+=y

In [21]:
len(n_Arxiv), len(n_Anth)

(77, 77)

Quite good method, gets most headings. Not all e.g. 7 conclusion and future works. Might perform better or worse for other papers. 
* Now needs cleaning: /n and -/n. 
* Numbers -> keep them i think. 
* Keep all parts that are the same? yeah. 
* vectorize parts 
* remove all parts that contain the wordt arxiv (first check no part of anthology contains arxiv.


In [22]:
import pandas as pd

In [32]:
df = pd.DataFrame(n_Anth, n_Arxiv).reset_index()
df.columns =['Anth', 'Arxiv' ]

In [33]:
df.columns

Index(['Anth', 'Arxiv'], dtype='object')

In [35]:
for i in range(len(df)):
    print(df['Anth'].iloc[i-1])
    print(df['Arxiv'].iloc[i-1])
    

Table 4: Results on validation and test set. Org. represents original
and Ext. represents extended. Base refers to baseline.

Table 4: Results on validation and test set. Org. represents original
and Ext. represents extended. Base refers to baseline.

Term Expansion and FinBERT fine-tuning for Hypernym and Synonym Ranking
of Financial Terms

Term Expansion and FinBERT fine-tuning for Hypernym and Synonym Ranking
of Financial Terms

Ankush Chopra∗† , Sohom Ghosh†

Ankush Chopra∗† , Sohom Ghosh†

Fidelity Investments, AI CoE, Bengaluru, India
{ankush01729, sohom1ghosh}@gmail.com

Fidelity Investments, AI CoE, Bengaluru, India
{ankush01729, sohom1ghosh}@gmail.com

Abstract

Abstract

 Hypernym and synonym matching are one of the
mainstream Natural Language Processing (NLP)
tasks. In this paper, we present systems that at-
tempt to solve this problem.
We designed these
systems to participate in the FinSim-3, a shared
task of FinNLP workshop at IJCAI-2021.
The
shared task is focused on solvin

In [36]:
df.iloc[2]

Anth     Fidelity Investments, AI CoE, Bengaluru, India...
Arxiv    Fidelity Investments, AI CoE, Bengaluru, India...
Name: 2, dtype: object

In [38]:
# 
# df

In [39]:
df['clean_Anth'] = df['Anth'].apply(clean_n)
df['clean_Arxiv'] = df['Arxiv'].apply(clean_n)

In [40]:
df

Anth  \
0   Term Expansion and FinBERT fine-tuning for Hype...   
1                    Ankush Chopra∗† , Sohom Ghosh†\n   
2   Fidelity Investments, AI CoE, Bengaluru, India...   
3                                          Abstract\n   
4    Hypernym and synonym matching are one of the\...   
..                                                ...   
72                   BERT\nExt.\n1.153\n0.928\n-\n-\n   
73    FinBERT(S1)\nOrg.\n1.117\n0.928\n1.257\n0.886\n   
74    FinBERT(S2)\nExt.\n1.110\n0.942\n1.220\n0.895\n   
75      SBERT(S3)\nExt.\n1.086\n0.947\n1.156\n0.917\n   
76  Table 4: Results on validation and test set. O...   

                                                Arxiv  \
0   Term Expansion and FinBERT fine-tuning for Hype...   
1                    Ankush Chopra∗† , Sohom Ghosh†\n   
2   Fidelity Investments, AI CoE, Bengaluru, India...   
3                                          Abstract\n   
4    Hypernym and synonym matching are one of the\...   
..                                                ...   
72                   BERT\nExt.\n1.153\n0.928\n-\n-\n   
73    FinBERT(S1)\nOrg.\n1.117\n0.928\n1.257\n0.886\n   
74    FinBERT(S2)\nExt.\n1.110\n0.942\n1.220\n0.895\n   
75      SBERT(S3)\nExt.\n1.086\n0.947\n1.156\n0.917\n   
76  Table 4: Results on validation and test set. O...   

                                           clean_Anth  \
0   Term Expansion and FinBERT fine-tuning for Hype...   
1                     Ankush Chopra∗† , Sohom Ghosh†    
2   Fidelity Investments, AI CoE, Bengaluru, India...   
3                                           Abstract    
4    Hypernym and synonym matching are one of the ...   
..                                                ...   
72                             BERT Ext. 1.153 0.928    
73          FinBERT(S1) Org. 1.117 0.928 1.257 0.886    
74          FinBERT(S2) Ext. 1.110 0.942 1.220 0.895    
75            SBERT(S3) Ext. 1.086 0.947 1.156 0.917    
76  Table 4: Results on validation and test set. O...   

                                          clean_Arxiv  
0   Term Expansion and FinBERT fine-tuning for Hype...  
1                     Ankush Chopra∗† , Sohom Ghosh†   
2   Fidelity Investments, AI CoE, Bengaluru, India...  
3                                           Abstract   
4    Hypernym and synonym matching are one of the ...  
..                                                ...  
72                             BERT Ext. 1.153 0.928   
73          FinBERT(S1) Org. 1.117 0.928 1.257 0.886   
74          FinBERT(S2) Ext. 1.110 0.942 1.220 0.895   
75            SBERT(S3) Ext. 1.086 0.947 1.156 0.917   
76  Table 4: Results on validation and test set. O...  

[77 rows x 4 columns]

In [61]:
df['clean_Anth'].iloc[3]

'Abstract '

In [64]:
df['clean_Anth'].iloc[3], df['clean_Arxiv'].iloc[3]

('Abstract ', 'Abstract ')

In [41]:
import tensorflow_hub as hub

embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")


In [82]:
e_both = embed([df['clean_Anth'].iloc[3], df['clean_Arxiv'].iloc[3]])
# e_Arxiv = embed()

# print(e_Arxiv, e_Anth)
print(e_both)
cosine_similarity(e_both)

tf.Tensor(
[[-0.0660406   0.03597628  0.08232541 ... -0.02758392 -0.06031669
  -0.01588463]
 [-0.0660406   0.03597628  0.08232541 ... -0.02758392 -0.06031669
  -0.01588463]], shape=(2, 512), dtype=float32)


array([[0.9999999, 0.9999999],
       [0.9999999, 0.9999999]], dtype=float32)

In [85]:
e_Anth = embed(df['clean_Anth'])
e_Arxiv = embed(df['clean_Arxiv'])

print(e_Arxiv, e_Anth)



tf.Tensor(
[[ 0.06068841 -0.08901937  0.009689   ... -0.00118487 -0.00935884
   0.01548933]
 [ 0.06970452 -0.03407925  0.04807003 ... -0.08015236  0.01355954
  -0.05697582]
 [ 0.0460197  -0.00676592 -0.0265883  ...  0.05534033 -0.07345361
  -0.08141246]
 ...
 [-0.05944481 -0.0490467   0.02642503 ... -0.01587217  0.02697126
   0.00699797]
 [-0.01973367 -0.05383429  0.02668439 ... -0.05047641  0.03337703
   0.0107846 ]
 [ 0.03363169 -0.08258406 -0.00992958 ...  0.01526111  0.01070202
  -0.0352058 ]], shape=(77, 512), dtype=float32) tf.Tensor(
[[ 0.06068841 -0.08901937  0.009689   ... -0.00118487 -0.00935884
   0.01548933]
 [ 0.06970452 -0.03407925  0.04807003 ... -0.08015236  0.01355954
  -0.05697582]
 [ 0.0460197  -0.00676592 -0.0265883  ...  0.05534033 -0.07345361
  -0.08141246]
 ...
 [-0.05944481 -0.0490467   0.02642503 ... -0.01587217  0.02697126
   0.00699797]
 [-0.01973367 -0.05383429  0.02668439 ... -0.05047641  0.03337703
   0.0107846 ]
 [ 0.03363169 -0.08258406 -0.00992958 ...  

In [87]:
result  = cosine_similarity(e_Anth, e_Arxiv)
result

array([[ 1.0000002 ,  0.0072812 ,  0.0939659 , ...,  0.04023684,
         0.11238029,  0.17212136],
       [ 0.0072812 ,  1.        ,  0.15659754, ...,  0.23801717,
         0.32555997, -0.06540015],
       [ 0.0939659 ,  0.15659754,  1.        , ...,  0.11673675,
         0.15190855,  0.01112158],
       ...,
       [ 0.04023684,  0.23801717,  0.11673675, ...,  1.        ,
         0.6585305 ,  0.06733611],
       [ 0.11238029,  0.32555997,  0.15190855, ...,  0.6585305 ,
         1.0000001 ,  0.05017748],
       [ 0.17212136, -0.06540016,  0.01112157, ...,  0.0673361 ,
         0.05017751,  1.        ]], dtype=float32)

In [88]:
result.shape

(77, 77)

In [89]:
e_Arxiv.shape

TensorShape([77, 512])

In [ ]:
# import tensorflow_hub as hub

# embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
# embeddings = embed([s_Anth, s_Arx])

# print(embeddings)

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

In [99]:
# cannot take the average, some parts are larger then others. Titles are 1. And small piece of text. Will skew the result.
for i in range(77):
    print(cosine_similarity(e_Anth[i].reshape(1,-1), e_Arxiv[i].reshape(1,-1)))

[[1.0000001]]
[[1.]]
[[1.]]
[[1.]]
[[0.99847585]]
[[1.]]
[[0.9903998]]
[[0.9999999]]
[[0.99277234]]
[[1.]]
[[1.0000001]]
[[0.9999999]]
[[0.26552123]]
[[1.]]
[[1.]]
[[0.99999994]]
[[1.]]
[[1.0000002]]
[[1.0000001]]
[[0.9999999]]
[[0.9082912]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.0000001]]
[[1.]]
[[1.0000001]]
[[1.]]
[[1.]]
[[1.]]
[[1.0000001]]
[[0.99999994]]
[[1.]]
[[1.]]
[[1.]]
[[0.99999994]]
[[0.9999999]]
[[1.]]
[[1.0000001]]
[[0.9460838]]
[[1.]]
[[1.0000001]]
[[1.]]
[[1.]]
[[1.]]
[[1.0000001]]
[[0.99888074]]
[[1.0000001]]
[[1.0000002]]
[[1.0000002]]
[[1.]]
[[1.]]
[[0.9999999]]
[[1.]]
[[1.0000001]]
[[0.99999994]]
[[1.]]
[[1.0000001]]
[[1.]]
[[1.]]
[[1.0000001]]
[[1.]]
[[1.0000001]]
[[0.9958594]]
[[1.]]
[[1.]]
[[1.0000001]]
[[1.]]
[[0.99999994]]
[[1.0000001]]
[[1.]]
[[1.]]
[[1.0000002]]
[[1.]]
[[1.]]


In [93]:
e_Anth

<tf.Tensor: shape=(77, 512), dtype=float32, numpy=
array([[ 0.06068841, -0.08901937,  0.009689  , ..., -0.00118487,
        -0.00935884,  0.01548933],
       [ 0.06970452, -0.03407925,  0.04807003, ..., -0.08015236,
         0.01355954, -0.05697582],
       [ 0.0460197 , -0.00676592, -0.0265883 , ...,  0.05534033,
        -0.07345361, -0.08141246],
       ...,
       [-0.05944481, -0.0490467 ,  0.02642503, ..., -0.01587217,
         0.02697126,  0.00699797],
       [-0.01973367, -0.05383429,  0.02668439, ..., -0.05047641,
         0.03337703,  0.0107846 ],
       [ 0.03363169, -0.08258406, -0.00992958, ...,  0.01526111,
         0.01070202, -0.0352058 ]], dtype=float32)>

In [96]:
from tensorflow.python.ops.numpy_ops import np_config
np_config.enable_numpy_behavior()
e_Anth[1].reshape(1,-1)

<tf.Tensor: shape=(1, 512), dtype=float32, numpy=
array([[ 6.97045177e-02, -3.40792537e-02,  4.80700321e-02,
         1.10333441e-02,  9.67413634e-02, -4.06522155e-02,
         5.80488555e-02,  1.21750701e-02,  3.73702087e-02,
         3.01103964e-02,  1.46108782e-02, -1.76529419e-02,
         2.12727226e-02, -1.84823908e-02,  4.91663404e-02,
        -4.81386855e-03,  3.57749052e-02, -5.06638624e-02,
        -3.00153997e-02,  4.16631028e-02,  2.80601811e-02,
         3.03535871e-02, -3.44741829e-02,  4.79683690e-02,
        -1.54933454e-02, -1.26457773e-02,  2.48310398e-02,
         1.55036226e-02,  2.29931939e-02,  6.50966167e-02,
        -5.92529355e-03,  7.20450878e-02, -2.10878719e-02,
        -6.03301488e-02,  8.38561505e-02,  5.64505309e-02,
        -5.87900020e-02,  2.18304154e-02, -9.02495235e-02,
         2.74714287e-02, -4.52572256e-02, -5.38781025e-02,
         5.10093905e-02,  9.02677886e-03,  9.32785310e-03,
         1.37680694e-02, -7.02025555e-03,  2.62791826e-03,
      